### ISSUE TITLE
not display icon

### ISSUE THREAD

**Issue by tbago** [royclarkson/xcode-templates#4]
The scrip worked perfect.But when create file template,not display icon file.Would you like to fixed this issue?

**Comment by royclarkson** [comment]
I do not know how to fix it. Do you have a recommendation? Thanks.

**Comment by tbago** [comment]
I am not familiar with Ruby.So I replace the icon file with Xcode template icon by copy & paste.

**Comment by royclarkson** [comment]
Ah, I see. I can probably automate that with the script. What's the path to the icon you are using copying?

**Comment by tbago** [comment]
c++ image template file at the path
/Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/File\ Templates/Source/C++\ File.xctemplate/TemplateIcon@2x.png

**Comment by royclarkson** [comment]
Resolved by #5
